<?php

return [
    'default_model' => 'gpt-4o',
    'default_max_tokens' => 150,
    'default_temperature' => 0.7,
    'default_image_size' => '1024x1024',
    'image_model' => 'dall-e-3',
    'image_storage_disk' => 'public',
    'image_storage_path' => 'ai-generated-images',
    
    'content_templates' => [
        'service_update_notification' => 'Notify customers about an upcoming service maintenance window affecting [area] on [date].',
        'outage_alert' => 'Craft a message to inform clients about an unexpected service outage in [area] and provide estimated resolution time.',
        'billing_reminder' => 'Write a polite reminder to inform a customer about their upcoming bill payment due date for [service name].',
        'upgrade_offer' => 'Create a message to offer an upgrade to a higher-speed internet package or bundle.',
        'service_confirmation' => 'Compose a confirmation message for a successful service setup or activation for [service name] in [customer location].',
        'payment_received' => 'Send a confirmation message to a client acknowledging receipt of their recent payment for [service name].',
        'promotional_discount' => 'Inform customers about a limited-time discount or promotion for [specific service or package].',
        'speed_test_prompt' => 'Encourage clients to use a speed test to verify their internet performance and to contact support if issues arise.',
        'account_activation_instructions' => 'Provide clear instructions for new customers to activate their account for [service name].',
        'customer_feedback_request' => 'Request feedback from a customer on their recent installation or support experience for [service name].',
        'contract_renewal_reminder' => 'Remind clients of their upcoming contract renewal date and options for renewal or upgrades.',
        'security_advisory' => 'Send a security advisory to inform customers about best practices for secure internet usage.',
        'network_upgrade_notification' => 'Notify clients about planned network upgrades in [specific area] and expected improvements in service.',
        'holiday_greeting' => 'Craft a holiday greeting message to thank clients for their loyalty and wish them well during the holiday season.',
        'technical_support_follow_up' => 'Compose a follow-up message to check if a recent technical support issue has been fully resolved to the customer’s satisfaction.',
    ],

    'template_placeholders' => [
        'service_update_notification' => 'Write the affected area and maintenance date',
        'outage_alert' => 'Write the affected area and estimated resolution time',
        'billing_reminder' => 'Write the service name',
        'upgrade_offer' => 'Write the upgraded package details',
        'service_confirmation' => 'Write the service name and customer location',
        'payment_received' => 'Write the service name',
        'promotional_discount' => 'Write the service or package name',
        'speed_test_prompt' => 'Write any additional troubleshooting tips',
        'account_activation_instructions' => 'Write activation steps for the service',
        'customer_feedback_request' => 'Write the service name or type of recent interaction',
        'contract_renewal_reminder' => 'Write the contract renewal date or options',
        'security_advisory' => 'Write security tips or practices',
        'network_upgrade_notification' => 'Write the specific area and improvement details',
        'holiday_greeting' => 'Write the holiday name or greeting details',
        'technical_support_follow_up' => 'Write the issue or support case reference',
    ],
    
    'image_prompts' => [
        'product_showcase' => 'A professional photo of [product] on a white background.',
        'nature_scene' => 'A serene landscape featuring [natural elements].',
        'abstract_concept' => 'An abstract representation of [concept] using vibrant colors.',
        'character_portrait' => 'A detailed portrait of a [character description].',
        'food_photography' => 'A mouth-watering close-up of [dish name].',
        'tech_illustration' => 'A futuristic illustration of [technology].',
        'fashion_design' => 'A stylish outfit featuring [clothing items and style].',
        'book_cover' => 'A captivating book cover design for a [genre] novel titled [book name].',
        'logo_concept' => 'A minimalist logo design for a company named [company name].',
        'infographic_element' => 'A clean and modern infographic element representing [data or concept].',
    ],

    // Add Image prompt placeholders here
    'prompt_placeholders' => [
        'product_showcase' => 'Write your product name',
        'nature_scene' => 'Write natural elements',
        'abstract_concept' => 'Write your concept',
        'character_portrait' => 'Describe the character',
        'food_photography' => 'Write the dish name',
        'tech_illustration' => 'Write the technology name',
        'fashion_design' => 'Write clothing items & style',
        'book_cover' => 'Write Genre & Book name',
        'logo_concept' => 'Write the company name',
        'infographic_element' => 'Explain the data or concept',
    ],
];